zram-y	:=	zram_drv.o zram_sysfs.o xvmalloc.o lzo1x_decompress.o lzo1x_compress.o

obj-$(CONFIG_ZRAM)	+=	zram.o



#lzo_compress-objs := lzo1x_compress.o
#lzo_decompress-objs := lzo1x_decompress.o

#obj-$(CONFIG_LZO_COMPRESS) += lzo_compress.o
#obj-$(CONFIG_LZO_DECOMPRESS) += lzo_decompress.o
